- name: Configure OSPF
  hosts: nexus
  gather_facts: no
  connection: local

  vars:
    nxos:
      username: admin
      password: admin
      transport: nxapi
      host: "{{ inventory_hostname }}"


  tasks:
    - name: Prep physical interfaces
      nxos_interface:
        interface: "{{ item.interface }}"
        mode:  "{{ item.mode }}"
        admin_state: up
        provider: "{{ nxos }}"
      with_items: "{{ phys_intf }}"

    - name: Configure IP Addressing Per Interface
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        version: v4
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        state: present
        provider: "{{ nxos }}"
      with_items: "{{ addr_intf }}"


    - name: Configure OSPF Domain
      nxos_ospf:
        ospf: 1
        state: present
        provider: "{{ nxos }}"


    - name: Configuring OSPF Interface Parameters
      nxos_interface_ospf:
        interface: "{{ item.interface }}"
        ospf: 1
        area: 0
        dead_interval: 4
        hello_interval: 1
        provider: "{{ nxos }}"
      with_items: "{{ ospf_intf }}"
      
    - name: Save Running Config if Modified
      nxos_config:
        save_when: modified
        timeout: 30
        provider: "{{ nxos }}"
