- hosts: glusternodes
  remote_user: root

  tasks:
  - name: Update apt cache repository
    apt:
        update_cache: yes

  - name: Upgrade all packages
    apt:
        upgrade: dist

  - name: Install ntpdate client
    apt:
        name: ntpdate
        state: present

  - name: Upload ntpdate client file
    copy:
         src: /etc/ansible/files/ntpdate
         dest: /etc/default/ntpdate
         owner: root
         group: root
         mode: 0644
         backup: yes

  - name: Execute ntpdate
    command: ntpdate-debian

  - name: copy .bashrc file to node(s)
    copy:
         src: ~/.bashrc
         dest: ~/.bashrc
         owner: root
         group: root
         mode: 0644
         backup: yes

  - name: Install glusterfs on node(s)
    apt:
        name: glusterfs-server
        state: present
