---

- name: VPC Configurations
  hosts: switches
  gather_facts: no
  connection: local

  vars:
    nxos:
      username: admin
      password: admin
      transport: nxapi
      host: "{{ inventory_hostname }}"


  tasks:
    - name: Enable Required Features for Proper Operation
      nxos_feature:
        feature: "{{ item.feature }}"
        provider: "{{ nxos }}"
      with_items: "{{ enable_features }}"

    - name: Configure VPC parameters
      nxos_vpc:
        auto_recovery: true
        domain: 200
        peer_gw: true
        pkl_vrf: management
        pkl_dest: "{{ item.pkl_dest }}"
        pkl_src: "{{ item.pkl_src }}"
        state: present
        provider: "{{ nxos }}"
      with_items: "{{ vpc_config }}"

    - name: Assign interfaces as members to port-channel
      nxos_portchannel:
        group: 10
        members: ['Ethernet1/1', 'Ethernet1/2']
        mode: active
        state: present
        provider: "{{ nxos }}"

    - name: Configure port-channel as a trunk
      nxos_switchport:
        interface: port-channel10
        mode: trunk
        provider: "{{ nxos }}"

    - name: Assign interface to VPC
      nxos_vpc_interface:
        portchannel: 10
        peer_link: true
        state: present
        provider: "{{ nxos }}"

    - name: Ensure interfaces are active
      nxos_interface:
        interface: "{{ item.interface }}"
        state: present
        provider: "{{ nxos }}"
      with_items: "{{ phys_intf }}"

    - name: Save running config if modified
      nxos_config:
        save_when: modified
        timeout: 30
        provider: "{{ nxos }}"
