---

- name: Stage 9K Switching Environment
  hosts: switches
  gather_facts: no
  connection: local

  vars:
    nxos:
      username: admin
      password: admin
      transport: nxapi
      host: "{{ inventory_hostname }}"

  tasks:

    - name: Enable required feature sets
      nxos_feature:
        feature: "{{ item.feature }}"
        provider: "{{ nxos }}"
      with_items: "{{ features }}"

    - name: Create necessary vlan IDs and Names
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
        provider: "{{ nxos }}"
      with_items: "{{ vlans }}"

    - name: Create SVI Interfaces
      nxos_interface:
        interface: "{{ item.interface }}"
        description: "{{ item.description }}"
        provider: "{{ nxos }}"
      with_items: "{{ svi_interfaces }}"

    - name: Create loopback interfaces
      nxos_interface:
        interface: "{{ item.interface }}"
        description: "{{ item.description }}"
        provider: "{{ nxos }}"
      with_items: "{{ loopback_interfaces }}"

    - name: Create L3 configs for SVI
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        provider: "{{ nxos }}"
      with_items: "{{ svi_interface_addr }}"


    - name: Add IP addresses to loopbacks
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        provider: "{{ nxos }}"
      with_items: "{{ loopbacks }}"

    - name: Configure VPC parameters
      nxos_vpc:
        auto_recovery: true
        domain: 100
        peer_gw: true
        pkl_vrf: management
        pkl_dest: "{{ item.pkl_dest }}"
        pkl_src: "{{ item.pkl_src }}"
        state: present
        provider: "{{ nxos }}"
      with_items: "{{ vpc_config }}"

    - name: Assign interfaces as members to port-channel
      nxos_portchannel:
        group: 10
        members: ['Ethernet1/8', 'Ethernet1/9']
        mode: active
        state: present
        provider: "{{ nxos }}"

    - name: Configure port-channel as a trunk
      nxos_switchport:
        interface: port-channel10
        mode: trunk
        provider: "{{ nxos }}"

    - name: Assign interface as a VPC peer-link
      nxos_vpc_interface:
        portchannel: 10
        peer_link: true
        state: present
        provider: "{{ nxos }}"

    - name: Ensure member port-channel interfaces are up
      nxos_interface:
        interface: "{{ item.interface }}"
        state: present
        provider: "{{ nxos }}"
      with_items: "{{ physical_intf }}"
      
    - name: Enabling OSPF
      nxos_feature:
        feature: ospf
        provider: "{{ nxos }}"

    - name: Configuring OSPF domain
      nxos_ospf:
        ospf: 1
        state: present
        provider: "{{ nxos }}"

    - name: Configuring OSPF Interface Parameters
      nxos_interface_ospf:
        interface: "{{ item.interface }}"
        ospf: 1
        area: 0
        dead_interval: 4
        hello_interval: 1
        provider: "{{ nxos }}"
      with_items: "{{ ospf_interfaces }}"

    - name: Save running config if modified
      nxos_config:
        save_when: modified
        timeout: 30
        provider: "{{ nxos }}"
