---

- name: Stage 9K Switching Environment
  hosts: switches
  gather_facts: no
  connection: local

  vars:
    nxos:
      username: admin
      password: admin
      transport: nxapi
      host: "{{ inventory_hostname }}"


  tasks:

    - name: Enable required feature sets
      nxos_feature:
        feature: "{{ item.feature }}"
        provider: "{{ nxos }}"
      with_items: "{{ features }}"

    - name: Create necessary vlan IDs and Names
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
        provider: "{{ nxos }}"
      with_items: "{{ vlans }}"

    - name: Create SVI Interfaces
      nxos_interface:
        interface: "{{ item.interface }}"
        description: "{{ item.description }}"
        provider: "{{ nxos }}"
      with_items: "{{ svi_interfaces }}"

    - name: Create loopback interfaces
      nxos_interface:
        interface: "{{ item.interface }}"
        description: "{{ item.description }}"
        provider: "{{ nxos }}"
      with_items: "{{ loopback_interfaces }}"


    - name: Create L3 configs for SVI
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        provider: "{{ nxos }}"
      with_items: "{{ svi_interface_addr }}"


    - name: Add IP addresses to loopbacks
      nxos_ip_interface:
        interface: "{{ item.interface }}"
        addr: "{{ item.addr }}"
        mask: "{{ item.mask }}"
        provider: "{{ nxos }}"
      with_items: "{{ loopbacks }}"

    - name: Save running config if modified
      nxos_config:
        save_when: modified
        timeout: 30
        provider: "{{ nxos }}"
