---

hostnames:
- { hostname: bgp-2 }

addr_intf:
- { interface: Ethernet1/2, addr: 10.0.0.1, mask: 31 }
- { interface: Ethernet1/1, addr: 10.0.0.4, mask: 31 }
- { interface: Loopback0, addr: 172.16.255.253, mask: 32 }

routerid:
- { router_id: 172.16.255.253 }

ibgp_neighbors:
- { neighbor: 172.16.255.254 }

ebgp_neighbors:
- { neighbor: 10.0.0.5 }
